# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zeV90FbfMigPXROM9ZbiRcw3ylhq9-tr
"""

num1 = int(input("Enter Number 1:"))
num2 = int(input("Enter Number 2:"))

result = num1 + num2
print(num1," + ",num2," = ",result)

x = 5
type(x)

x = (str(x))

type(x)

a_variable = 55

print(f"There are {a_variable} people")

language1 = "python"
language2 = "java"

print(language1 + "\n" + language2)

print(language1, language2)





